<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.zscript.maven-templates.it</groupId>
    <artifactId>absolute-template-directory</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <build>
        <plugins>
            <plugin>
                <groupId>net.zscript.maven-templates</groupId>
                <artifactId>mustache-templating-maven-plugin</artifactId>
                <version>@project.version@</version>
                <configuration>
                    <outputDirectory>${project.build.directory}/generated-text</outputDirectory>
                    <templateDirectory>${project.basedir}/src/main/templates/with spaces</templateDirectory>
                    <mainTemplate>test-absolute.mustache</mainTemplate>
                    <fileTypeSuffix>txt</fileTypeSuffix>
                    <contexts>
                        <includes>exampleA-1.yaml</includes>
                    </contexts>
                </configuration>
                <executions>
                    <execution>
                        <id>absolute-template-directory</id>
                        <goals>
                            <goal>transform</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
